#' Example inputs for `call_episomal_ecdna()`
#'
#' A small, self-contained toy dataset describing a textbook **episomal EGFR
#' ecDNA** on chr7 in a fictional sample `"EXAMPLE01"`: a focal amplification
#' bounded by a high variant-fraction duplication (the circularisation
#' junction), excised from otherwise diploid flanks and leaving a low-VF
#' deletion "excision scar". The data are synthetic (no patient data) so the
#' example runs anywhere in seconds and `call_episomal_ecdna()` flags the
#' amplicon as episomal.
#'
#' @format A named `list` of four [GenomicRanges::GRanges] objects, matching the
#'   four required arguments of [call_episomal_ecdna()]:
#' \describe{
#'   \item{`ecdna_gr`}{AmpliconArchitect-style ecDNA amplicon region; metadata `ID`, `WGS_ID`.}
#'   \item{`breakpoints_gr`}{PURPLE-style SV breakpoints; metadata `WGS_ID`, `event`, `svclass`, `PURPLE_AF`, `PURPLE_JCN`, `VF`, `PURPLE_CN`, `insLen`, `HOMLEN`.}
#'   \item{`cnv_gr`}{PURPLE-style allele-specific copy-number segments; metadata `sample`, `copyNumber`, `ploidy`, `majorAlleleCopyNumber`, `minorAlleleCopyNumber`.}
#'   \item{`cancer_genes_gr`}{Cancer-gene loci (EGFR) with a `gene` column.}
#' }
#' @source Synthetic; generated by `data-raw/make_example_data.R`.
#' @seealso [call_episomal_ecdna()], [ex_plot_inputs]
#' @examples
#' res <- call_episomal_ecdna(
#'   ex_caller_inputs$ecdna_gr, ex_caller_inputs$breakpoints_gr,
#'   ex_caller_inputs$cnv_gr,   ex_caller_inputs$cancer_genes_gr
#' )
#' res$episomal
"ex_caller_inputs"

#' Example inputs for `plot_sv_linear()`
#'
#' The same episomal EGFR ecDNA as [ex_caller_inputs], expressed in the
#' data-frame format expected by [plot_sv_linear()] for sample `"EXAMPLE01"`.
#' `karyotype` and `gene_coord` are omitted so the plotter falls back to the
#' bundled hg38 references.
#'
#' @format A named `list` of three `data.frame`s:
#' \describe{
#'   \item{`cnv_data`}{Copy-number segments; columns `sample`, `seqnames`, `start`, `end`, `copyNumber`, `ploidy`, `majorAlleleCopyNumber`, `minorAlleleCopyNumber`.}
#'   \item{`sv_data`}{Structural variants; columns `chrom1`, `start1`, `chrom2`, `start2`, `strand1`, `strand2`, `svclass`, `VF`, `JCN`, `sample`.}
#'   \item{`wgd_data`}{Whole-genome-duplication status; columns `sample`, `Polyploidy`.}
#' }
#' @source Synthetic; generated by `data-raw/make_example_data.R`.
#' @seealso [plot_sv_linear()], [ex_caller_inputs]
#' @examples
#' p <- plot_sv_linear(
#'   sample   = "EXAMPLE01",
#'   cnv_data = ex_plot_inputs$cnv_data,
#'   sv_data  = ex_plot_inputs$sv_data,
#'   wgd_data = ex_plot_inputs$wgd_data,
#'   chromosome = "chr7"
#' )
"ex_plot_inputs"

#' Example small mutations with a kataegis cluster
#'
#' Synthetic SNVs for sample `"EXAMPLE01"` on chr7, in the format
#' [plot_sv_linear()] expects for its optional `snv_data` panel: a localised
#' **kataegis** shower of APOBEC-like C>N substitutions over the EGFR amplicon
#' (short intermutation distances) plus a few scattered background SNVs. Passed
#' to `plot_sv_linear(snv_data = ex_snv)` it adds a rainfall panel in which the
#' kataegis cluster dips toward the bottom.
#'
#' @format A `data.frame` with columns `sampleID`, `seqnames`, `start`,
#'   `allelic_freq`, `variant_cn`, `type`, `ref`, `mut`.
#' @source Synthetic; generated by `data-raw/make_example_data.R`.
#' @seealso [plot_sv_linear()], [ex_plot_inputs]
#' @examples
#' p <- plot_sv_linear(
#'   sample   = "EXAMPLE01",
#'   cnv_data = ex_plot_inputs$cnv_data,
#'   sv_data  = ex_plot_inputs$sv_data,
#'   chromosome = "chr7", chromosome_range = matrix(c(54e6, 56e6), nrow = 1),
#'   snv_data = ex_snv
#' )
"ex_snv"

#' Example inputs for `plot_sv_reconstruction()`: the DO11501T1 CDK4 amplicon
#'
#' A real, complex focal amplification -- the **CDK4** amplicon on chr12 in
#' tumour sample `"DO11501T1"` -- carrying hundreds of structural-variant
#' junctions across a wide read-support (`VF`) range, so
#' [plot_sv_reconstruction()] can rebuild it wave by wave from the highest-`VF`
#' founder down. `karyotype` / `gene_coord` fall back to the bundled hg38
#' references (CDK4 is labelled).
#'
#' @format A named `list` of three `data.frame`s -- `cnv_data`, `sv_data`,
#'   `wgd_data` -- matching the columns [plot_sv_reconstruction()] expects
#'   (chr12, ~56-61 Mb around CDK4).
#' @source Copy-number segments and SV junctions for sample DO11501T1, subset to
#'   the chr12 CDK4 region; generated by `data-raw/make_example_data.R`.
#' @seealso [plot_sv_reconstruction()], [ex_plot_inputs]
#' @examples
#' p <- plot_sv_reconstruction(
#'   sample   = "DO11501T1",
#'   cnv_data = ex_recon_inputs$cnv_data,
#'   sv_data  = ex_recon_inputs$sv_data,
#'   wgd_data = ex_recon_inputs$wgd_data,
#'   chromosome = "chr12", chromosome_range = matrix(c(57e6, 60e6), nrow = 1),
#'   min_vf = 10
#' )
"ex_recon_inputs"
